const createAssistantFully = require('./createAssistantFully'),
  deleteAssistantFully = require('./deleteAssistantFully'),
  exportAssistant = require('./exportAssistant'),
  initConfig = require('./initConfig'),
  listAssistants = require('./listAssistants'),
  resetAssistant = require('./resetAssistant'),
  updateAssistant = require('./updateAssistant'),
  importAssistant = require('./importAssistant'),
  importAlexaAssistant = require('./importAlexaAssistant'),
  gitTemplates = require('./get-templates'),
  customChannel = require('./customChannel'),
  bulkUploadFieldValues = require('./bulkUploadFieldValues'),
  existAssistantCheck = require('./existAssistantCheck');

module.exports = Object.assign({},
  createAssistantFully,
  deleteAssistantFully,
  exportAssistant,
  initConfig,
  listAssistants,
  resetAssistant,
  updateAssistant,
  importAssistant,
  importAlexaAssistant,
  gitTemplates,
  customChannel,
  bulkUploadFieldValues,
  existAssistantCheck
);